unit ondas;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  StdCtrls, Buttons, ExtCtrls, ComCtrls, jpeg, MPlayer, YRChrono;

type
  Tondas_frm = class(TForm)
    MediaPlayer1: TMediaPlayer;
    Timer2: TTimer;
    Image1: TImage;
    Image11: TImage;
    GroupBox1: TGroupBox;
    Edit12: TEdit;
    Edit15: TEdit;
    Edit16: TEdit;
    Edit14: TEdit;
    Edit17: TEdit;
    Panel2: TPanel;
    Button3: TButton;
    Button4: TButton;
    Panel11: TPanel;
    LCrono2: TLabel;
    Label235: TLabel;
    Label1: TLabel;
    Label2: TLabel;
    Label3: TLabel;
    Label5: TLabel;
    Label4: TLabel;
    Label10: TLabel;
    Label9: TLabel;
    Label8: TLabel;
    Label7: TLabel;
    Label6: TLabel;
    MyChrono: TYRChronometre;
    Timer3: TTimer;
    Label11: TLabel;
    Edit1: TEdit;
    Edit2: TEdit;
    Edit3: TEdit;
    Edit4: TEdit;
    Edit5: TEdit;
    CheckBox1: TCheckBox;
    GroupBox2: TGroupBox;
    CheckBox2: TCheckBox;
    CheckBox3: TCheckBox;
    CheckBox4: TCheckBox;
    CheckBox5: TCheckBox;
    CheckBox6: TCheckBox;
    CheckBox7: TCheckBox;
    CheckBox8: TCheckBox;
    CheckBox9: TCheckBox;
    CheckBox10: TCheckBox;
    CheckBox11: TCheckBox;
    CheckBox12: TCheckBox;
    CheckBox13: TCheckBox;
    CheckBox14: TCheckBox;
    CheckBox15: TCheckBox;
    CheckBox16: TCheckBox;
    CheckBox17: TCheckBox;
    CheckBox18: TCheckBox;
    CheckBox19: TCheckBox;
    CheckBox20: TCheckBox;
    CheckBox21: TCheckBox;
    CheckBox22: TCheckBox;
    Edit7: TEdit;
    CheckBox23: TCheckBox;
    CheckBox24: TCheckBox;
    CheckBox25: TCheckBox;
    CheckBox26: TCheckBox;
    TResonancias: TTimer;
    CheckBox27: TCheckBox;
    CheckBox28: TCheckBox;
    CheckBox29: TCheckBox;
    CheckBox30: TCheckBox;
    CheckBox31: TCheckBox;
    CheckBox32: TCheckBox;
    CheckBox33: TCheckBox;
    CheckBox34: TCheckBox;
    CheckBox35: TCheckBox;
    CheckBox36: TCheckBox;
    CheckBox37: TCheckBox;
    procedure FormCreate(Sender: TObject);
    procedure FormShow(Sender: TObject);
    procedure Timer2Timer(Sender: TObject);
    procedure Button3Click(Sender: TObject);
    procedure Button4Click(Sender: TObject);
    procedure Timer3Timer(Sender: TObject);
    procedure Panel2Click(Sender: TObject);
    procedure FormClose(Sender: TObject; var Action: TCloseAction);
    procedure Label11Click(Sender: TObject);
    procedure Edit6Change(Sender: TObject);
    procedure TResonanciasTimer(Sender: TObject);

  private
    { Private declarations }

    vleft , vtop : integer;

  public
    { Public declarations }


preg : Integer;
procedure LimpiarResonancias();
  end;

var
  ondas_frm: Tondas_frm;
  SS,aviPath   : String;
  Path : String;
  Attr,reaction  : Integer;
  SearchRec : TSearchRec;
  Result ,l, acu3  : Integer;
  PicName   : String;
  AscFreq : LongInt;
   dir,rb9 ,alg,x,coher :integer;
        pathh : string;
        ran3,ran4,ran33    : integer;

        implementation

{$R *.DFM}
 uses   freq2,UnitVol, Therapy, Testdata, Patname,wawp,Printers, Cnscios,
  DataMod, Urecompensa, CDPlayu, Spine;

 { Editor = 'write.exe' or 'notepad.exe'}
Procedure MyWinExec(Editor : String;Sfile : String);
Var S : String;
    S1: String;
    K : array[0..255] of char;
Begin
  GetDir(0,S); { 0 = Current drive }
  S:=ExtractFilePath(S);
  S:=S+'PROGRAM\'+Sfile;
   S1:=Editor+' '+S;
  StrPCopy(K,S1);
  Winexec(K,1);
end;


Function ReturnASCPlus(N : String) : LongInt;
Var  i : Integer;
     isum : LongInt;
Begin
  isum := 0;
  For i:=1 to Length(N) do isum:=isum+Ord(N[i]);
  Result:=isum;
End;

procedure Tondas_frm.FormCreate(Sender: TObject);
begin
DoubleBuffered:=true;
end;

procedure Tondas_frm.FormShow(Sender: TObject);
begin
DM.Bitacora('Carga Generador de Campo Orgón');
Button3.Click;
image11.picture := testForm1.Image2.picture;
image1.picture.LoadFromFile('fundir.jpg');
MyChrono.Start;
Timer3.enabled := true;
TResonancias.enabled := true;
Button4.Click;
End;

procedure Tondas_frm.Timer2Timer(Sender: TObject);
begin
Label235.Caption:=TimeToStr(Time);
Lcrono2.Caption := MyChrono.Time2Str(MyChrono.TimeElapsed) ;
end;

procedure Tondas_frm.Button3Click(Sender: TObject);
begin
oeg:=random(60);
if oeg<2 then edit12.text:='¡Tengo una paz increíble!';
if oeg=3 then edit12.text:='Abandono todos mis conflictos internos a fin de que venga a mí la paz mental.';
if oeg=4 then edit12.text:='Abandono todos mis juicios y mi tendencia a hacer comparaciones.';
if oeg=5 then edit12.text:='Abriré mi corazón y me perdonaré.';
if oeg=6 then edit12.text:='Abro mi corazón y acepto a los demás como son.';
if oeg=7 then edit12.text:='Abro mi corazón y me regocijo en lo que soy.';
if oeg=8 then edit12.text:='Abro mi imaginación para crear el mejor de los mundos para mí mismo.';
if oeg=9 then edit12.text:='Acepto a los demás tal como son.';
if oeg=10 then edit12.text:='Acepto con confianza mi grandeza y mantengo siempre esta autoestima.';
if oeg=11 then edit12.text:='Acepto el amor de todos los que lo ofrezcan.';
if oeg=12 then edit12.text:='Acepto el milagro de la curación y permito ser totalmente curado.';
if oeg=13 then edit12.text:='Acepto el placer como parte de mí ser.';
if oeg=14 then edit12.text:='Acepto la felicidad y la salvación ahora.';
if oeg=15 then edit12.text:='Acepto las opiniones o criterios dispares de los míos.';
if oeg=16 then edit12.text:='Acepto mis imperfecciones.';
if oeg=17 then edit12.text:='Acepto mis limitaciones interiores.';
if oeg=18 then edit12.text:='Ahora me permito Ser Feliz.';
if oeg=19 then edit12.text:='Ahora todo lo que necesito viene a mí.';
if oeg=20 then edit12.text:='Ahora trasciendo mis viejos miedos y limitaciones.';
if oeg=21 then edit12.text:='Amo al ser que está en mí.';
if oeg=22 then edit12.text:='Amo sin esperar nada a cambio.';
if oeg=23 then edit12.text:='Amo y soy amado.';
if oeg=24 then edit12.text:='Aprendo a escuchar y a confiar en mi voz interior.';
if oeg=25 then edit12.text:='Aprendo algo nuevo con cada experiencia.';
if oeg=26 then edit12.text:='Asumo el cuidado de mi mismo todo el tiempo.';
if oeg=27 then edit12.text:='Asumo la responsabilidad de mi propia vida. Soy Libre.';
if oeg=28 then edit12.text:='Atraigo gente con la moral muy alta.';
if oeg=29 then edit12.text:='Busco el amor y lo encuentro en todas partes.';
if oeg=30 then edit12.text:='Comparto mi afecto y mi gozo.';
if oeg=31 then edit12.text:='Comparto mi amor con los demás.';
if oeg=32 then edit12.text:='Comprendo todo aquello que debo saber o comprender.';
if oeg=33 then edit12.text:='Con alegría acepto y muestro el niño que hay en mí.';
if oeg=34 then edit12.text:='Con facilidad y amor pido lo que necesito.';
if oeg=35 then edit12.text:='Confío en el éxito final.';
if oeg=36 then edit12.text:='Confió en el proceso de la vida.';
if oeg=37 then edit12.text:='Confió en mi guía interior.';
if oeg=38 then edit12.text:='Confió en mi mismo, confió en mi intuición.';
if oeg=39 then edit12.text:='Confío en mí.';
if oeg=40 then edit12.text:='Confío en que el proceso de la vida cuidará de mí.';
if oeg=41 then edit12.text:='Conservo mis pensamientos claros y tranquilos en los grupos.';
if oeg=42 then edit12.text:='Consigo que nadie enturbie mi mirada.';
if oeg=43 then edit12.text:='Creo en mis hermanos y los acepto, los respaldo y los valoro.';
if oeg=44 then edit12.text:='Creo la paz en mi mente, mi cuerpo y mi mundo.';
if oeg=45 then edit12.text:='Cuanto más amor doy, más amor recibo.';
if oeg=46 then edit12.text:='Decido ver las cosas de manera diferente.';
if oeg=47 then edit12.text:='Decido vivir en el presente siempre jubiloso.';
if oeg=48 then edit12.text:='Declaro la paz y la armonía en mi interior y a mí alrededor.';
if oeg=49 then edit12.text:='Dejo el pasado y avanzo hacia lo nuevo.';
if oeg=50 then edit12.text:='Dejo partir mis conductas autodestructivas.';
if oeg=51 then edit12.text:='Dejo partir mis conductas emocionales y físicas.';
if oeg=52 then edit12.text:='Dejo partir mis viejos pensamientos. Lo pasado es pasado. Estoy en paz.';
if oeg=53 then edit12.text:='Dejo que el amor llegue a mi vida y me llene de felicidad y alegría.';
if oeg=54 then edit12.text:='Dejo que la Vida fluya a través de mí.';
if oeg=55 then edit12.text:='Dejo que salgan todos los bloqueos de energía.';
if oeg=56 then edit12.text:='Descubro lo maravilloso que soy.';
if oeg=57 then edit12.text:='Descubro mi propio don y lo realizo.';
if oeg=58 then edit12.text:='Deseo estar tranquilo.';
if oeg>59 then edit12.text:='Deshago todos mis pensamientos erróneos.';
 oeg:=random(60);
if oeg<2 then edit15.text:='Despierto mis poderes internos de autocuración.';
if oeg=3 then edit15.text:='Disfruto compartir con otros.';
if oeg=4 then edit15.text:='Disfruto con mi sexualidad.';
if oeg=5 then edit15.text:='Disfruto de ser libre y abierto a la bondad que me rodea.';
if oeg=6 then edit15.text:='Disfruto totalmente de todo lo que hago.';
if oeg=7 then edit15.text:='Doy a mi vida una finalidad y un destino.';
if oeg=8 then edit15.text:='Doy de todo corazón y alegremente y agradezco el privilegio de poder hacerlo.';
if oeg=9 then edit15.text:='Doy mi vida a mi niño interior bello y puro.';
if oeg=10 then edit15.text:='Elevo mi energía sexual.';
if oeg=11 then edit15.text:='Elijo aceptarme y amarme.';
if oeg=12 then edit15.text:='Elijo dejar que Dios decida por mí.';
if oeg=13 then edit15.text:='Elijo el amor como meta de felicidad.';
if oeg=14 then edit15.text:='Elijo la paz en lugar del conflicto.';
if oeg=15 then edit15.text:='Elijo llenar mi mundo de alegría.';
if oeg=16 then edit15.text:='En cada momento soy libre para decidir.';
if oeg=17 then edit15.text:='Encuentro dentro de mí lo que busco.';
if oeg=18 then edit15.text:='Encuentro en mi interior mi verdadera identidad.';
if oeg=19 then edit15.text:='Encuentro la paz en mi interior.';
if oeg=20 then edit15.text:='Encuentro mi camino y lo sigo con absoluta fe y confianza.';
if oeg=21 then edit15.text:='Encuentro mi propio ritmo.';
if oeg=22 then edit15.text:='Encuentro mi verdadera identidad.';
if oeg=23 then edit15.text:='Encuentro seguridad en mi interior.';
if oeg=24 then edit15.text:='Entiendo que el camino que recorro es el camino que yo he elegido.';
if oeg=25 then edit15.text:='Escojo hacer que mi vida sea sencilla, fácil y gozosa.';
if oeg=26 then edit15.text:='Escojo vivir en el espacio abierto de mi corazón.';
if oeg=27 then edit15.text:='Escucho mi voz interna. Ella me habla.';
if oeg=28 then edit15.text:='Escucho mis sentimientos y los expreso en forma apropiada.';
if oeg=29 then edit15.text:='Está bien expresar todas mis emociones.';
if oeg=30 then edit15.text:='Estoy a salvo, me relajo y dejo que la vida fluya jubilosamente.';
if oeg=31 then edit15.text:='Estoy a salvo.';
if oeg=32 then edit15.text:='Estoy abierto a la sabiduría interior.';
if oeg=33 then edit15.text:='Estoy abierto a nuevas experiencias.';
if oeg=34 then edit15.text:='Estoy abierto y receptivo a todos los puntos de vista.';
if oeg=35 then edit15.text:='Estoy consciente de cada instante de mi vida.';
if oeg=36 then edit15.text:='Estoy convencido de que mi curación será efectiva.';
if oeg=37 then edit15.text:='Estoy dispuesto a avanzar con soltura.';
if oeg=38 then edit15.text:='Estoy dispuesto a curarme.';
if oeg=39 then edit15.text:='Estoy dispuesto a tener éxito aunque suponga agradar a mis padres.';
if oeg=40 then edit15.text:='Estoy en manos de Dios.';
if oeg=41 then edit15.text:='Estoy en paz con todas mis emociones, me amo y me apruebo.';
if oeg=42 then edit15.text:='Estoy en paz con todos los aspectos de mi vida.';
if oeg=43 then edit15.text:='Estoy en paz.';
if oeg=44 then edit15.text:='Estoy libre de la influencia de traumas pasados.';
if oeg=45 then edit15.text:='Estoy lleno de energía y entusiasmo por la vida.';
if oeg=46 then edit15.text:='Estoy lleno de energía y entusiasmo.';
if oeg=47 then edit15.text:='Estoy rodeado de amor y lleno de paz.';
if oeg=48 then edit15.text:='Estoy sano, delgado y satisfecho.';
if oeg=49 then edit15.text:='Estoy seguro al ser yo.';
if oeg=50 then edit15.text:='Estoy seguro de mi capacidad de expresión.';
if oeg=51 then edit15.text:='Estoy seguro y a salvo cuando expreso mis sentimientos.';
if oeg=52 then edit15.text:='Estoy siempre a salvo y protegido.';
if oeg=53 then edit15.text:='Estoy totalmente abierto a un nuevo camino.';
if oeg=54 then edit15.text:='Expreso con facilidad mis sentimientos.';
if oeg=55 then edit15.text:='Expreso confianza en lo que digo y hago.';
if oeg=56 then edit15.text:='Expreso mi belleza y amor en todo lo que hago.';
if oeg=57 then edit15.text:='Expreso mi propia belleza y amor en todo lo que hago.';
if oeg=58 then edit15.text:='Fluyo fácilmente con el cambio.';
if oeg>59 then edit15.text:='Fluyo suavemente con la vida y en cada experiencia.';
 oeg:=random(60);
if oeg<2 then edit16.text:='Hablo con fluidez.';
if oeg=3 then edit16.text:='He sido creado perfecto y sigo así.';
if oeg=4 then edit16.text:='Hoy capto la maravilla y gloria de la vida con nuevos ojos.';
if oeg=5 then edit16.text:='Hoy comienzo una nueva vida.';
if oeg=6 then edit16.text:='Hoy descubro qué hago mejor, lo hago y disfruto haciéndolo.';
if oeg=7 then edit16.text:='Hoy es el día en que comienzo a hacer todas las cosas que deseé.';
if oeg=8 then edit16.text:='Hoy quiero trabajar la amabilidad, la bondad y la condescendencia.';
if oeg=9 then edit16.text:='Hoy sigo la voluntad de mi Padre.';
if oeg=10 then edit16.text:='Hoy sigo mi propio criterio, sin despreciar el ajeno.';
if oeg=11 then edit16.text:='Hoy trabajaré con la más pura de mis intenciones en mayor beneficio de todos.';
if oeg=12 then edit16.text:='Impulso mi vida con la energía que genero en el presente.';
if oeg=13 then edit16.text:='Irradio paz, calma y optimismo.';
if oeg=14 then edit16.text:='Jamás fracasaré porque he determinado triunfar.';
if oeg=15 then edit16.text:='Limpio mi cuerpo y mi ser continuamente.';
if oeg=16 then edit16.text:='Lleno mi corazón de paz y felicidad.';
if oeg=17 then edit16.text:='Me abro a una nueva vida.';
if oeg=18 then edit16.text:='Me acepto tal y como soy.';
if oeg=19 then edit16.text:='Me acepto y me apruebo tal cual soy.';
if oeg=20 then edit16.text:='Me acepto y me apruebo.';
if oeg=21 then edit16.text:='Me amo a mi mismo pase lo que pase.';
if oeg=22 then edit16.text:='Me amo a mí mismo.';
if oeg=23 then edit16.text:='Me amo tal y como soy.';
if oeg=24 then edit16.text:='Me amo y me apruebo.';
if oeg=25 then edit16.text:='Me amo y me apruebo. Soy perfecto. Estoy en paz.';
if oeg=26 then edit16.text:='Me atrevo a ver mi propio valor.';
if oeg=27 then edit16.text:='Me comunico fácil y alegremente.';
if oeg=28 then edit16.text:='Me doy permiso para cambiar.';
if oeg=29 then edit16.text:='Me doy permiso para disfrutar de mi cuerpo.';
if oeg=30 then edit16.text:='Me doy permiso para disfrutar totalmente de todo lo que hago.';
if oeg=31 then edit16.text:='Me doy permiso para estar en paz.';
if oeg=32 then edit16.text:='Me doy permiso para realizarme.';
if oeg=33 then edit16.text:='Me doy permiso para ser próspero y feliz.';
if oeg=34 then edit16.text:='Me encanta ser quien soy y hago valer mi poder con prudencia.';
if oeg=35 then edit16.text:='Me estoy limpiando de todos los residuos negativos.';
if oeg=36 then edit16.text:='Me expreso como soy fácilmente.';
if oeg=37 then edit16.text:='Me hallo en paz sabiendo que estoy protegido y guiado en todo momento.';
if oeg=38 then edit16.text:='Me liberaré de mis dudas recordando que hay una razón para todo lo que sucede.';
if oeg=39 then edit16.text:='Me libero de la necesidad de criticar a los demás.';
if oeg=40 then edit16.text:='Me libero de mis adicciones.';
if oeg=41 then edit16.text:='Me libero de mis programas del pasado.';
if oeg=42 then edit16.text:='Me libero de todo lo que limite mi desarrollo.';
if oeg=43 then edit16.text:='Me libero de todo lo que me hace daño.';
if oeg=44 then edit16.text:='Me libero del dolor y el sufrimiento.';
if oeg=45 then edit16.text:='Me libero del pasado.';
if oeg=46 then edit16.text:='Me lleno de saber para poder ayudar sabiamente.';
if oeg=47 then edit16.text:='Me perdono a mí mismo y decido por la felicidad.';
if oeg=48 then edit16.text:='Me perdono a mi mismo.';
if oeg=49 then edit16.text:='Me perdono completamente.';
if oeg=50 then edit16.text:='Me perdono por mis limitaciones.';
if oeg=51 then edit16.text:='Me permito estar conmigo mismo.';
if oeg=52 then edit16.text:='Me permito ser como soy.';
if oeg=53 then edit16.text:='Me quiero en presencia de los demás.';
if oeg=54 then edit16.text:='Me realizo creativamente.';
if oeg=55 then edit16.text:='Me respeto a mí mismo todo el tiempo.';
if oeg=56 then edit16.text:='Me rindo al amor.';
if oeg=57 then edit16.text:='Me siento amado y protegido.';
if oeg=58 then edit16.text:='Me siento bien y me sonrío.';
if oeg>59 then edit16.text:='Me siento despierto y fresco.';
 oeg:=random(60);
if oeg<2 then edit14.text:='Me siento dichoso porque conozco el amor y soy amado.';
if oeg=3 then edit14.text:='Me siento feliz conmigo mismo.';
if oeg=4 then edit14.text:='Me siento muy a gusto siguiendo una dieta sana.';
if oeg=5 then edit14.text:='Me siento seguro compartiendo mis sentimientos.';
if oeg=6 then edit14.text:='Me siento seguro recibiendo.';
if oeg=7 then edit14.text:='Me uno cada vez y cada día más a Dios.';
if oeg=8 then edit14.text:='Merezco felicidad y gozo.';
if oeg=9 then edit14.text:='Merezco lo mejor de la vida.';
if oeg=10 then edit14.text:='Merezco lo mejor para mi vida.';
if oeg=11 then edit14.text:='Merezco que se me den las cosas que necesito.';
if oeg=12 then edit14.text:='Merezco relaciones divertidas, fáciles y que me apoyen.';
if oeg=13 then edit14.text:='Merezco ser amado.';
if oeg=14 then edit14.text:='Merezco ser feliz.';
if oeg=15 then edit14.text:='Merezco tenerlo todo.';
if oeg=16 then edit14.text:='Mi aprendizaje aparece de forma distinta y en sitios y con gentes diferentes.';
if oeg=17 then edit14.text:='Mi corazón está repleto de fuerza y confianza.';
if oeg=18 then edit14.text:='Mi hogar es el Universo.';
if oeg=19 then edit14.text:='Miro tranquilo hacia lo profundo de mí ser.';
if oeg=20 then edit14.text:='Mis ingresos aumentan constantemente.';
if oeg=21 then edit14.text:='Nadie tiene razón ni se equivoca. Voy más allá de mi juicio.';
if oeg=22 then edit14.text:='No necesito perseguir nada con el fin de estar completo.';
if oeg=23 then edit14.text:='No necesito sufrir para conseguir la felicidad.';
if oeg=24 then edit14.text:='No soy inútil, sino alguien todopoderoso.';
if oeg=25 then edit14.text:='Ofrezco a los demás lo que he recibido.';
if oeg=26 then edit14.text:='Perdono con facilidad.';
if oeg=27 then edit14.text:='Permito que mis pensamientos sean libres.';
if oeg=28 then edit14.text:='Pienso, hago y consigo cosas positivas.';
if oeg=29 then edit14.text:='Pongo mis talentos al servicio de un todo mayor.';
if oeg=30 then edit14.text:='Pongo todo mi ser en cada acto de la vida.';
if oeg=31 then edit14.text:='Poseo energía y vitalidad para mis tareas de vida.';
if oeg=32 then edit14.text:='Practico la moderación en pensamiento y acción.';
if oeg=33 then edit14.text:='Puedo comunicar mi amor con el lenguaje del silencio.';
if oeg=34 then edit14.text:='Puedo hacerlo, lo haré y lo hago.';
if oeg=35 then edit14.text:='Puedo sentir como la vida es más y más intensa y hermosa.';
if oeg=36 then edit14.text:='Reafirmo todo mi poder personal.';
if oeg=37 then edit14.text:='Reclamo mi poder ahora.';
if oeg=38 then edit14.text:='Reconozco las necesidades de mi cuerpo.';
if oeg=39 then edit14.text:='Reconozco los mensajes de mi cuerpo.';
if oeg=40 then edit14.text:='Recuerdo siempre que el propósito de mi relación es compartir la luz y dar felicidad.';
if oeg=41 then edit14.text:='Respeto el territorio de cada uno.';
if oeg=42 then edit14.text:='Respeto la libertad y necesidades de los que amo.';
if oeg=43 then edit14.text:='Respeto las creencias de los demás.';
if oeg=44 then edit14.text:='Respondo a las necesidades de otros sin alterar mi ser interior.';
if oeg=45 then edit14.text:='Restituyo mi energía bloqueada.';
if oeg=46 then edit14.text:='Revitalizo mi cuerpo y mi espíritu.';
if oeg=47 then edit14.text:='Satisfago plenamente todas mis necesidades.';
if oeg=48 then edit14.text:='Siempre estoy seguro y a salvo completamente en mi cuerpo físico.';
if oeg=49 then edit14.text:='Siempre tomo el camino correcto.';
if oeg=50 then edit14.text:='Siento fortaleza y coraje interno.';
if oeg=51 then edit14.text:='Siento la vida llena de alegría y de amor.';
if oeg=52 then edit14.text:='Siento mi armonía interna.';
if oeg=53 then edit14.text:='Siento mi fortaleza interna.';
if oeg=54 then edit14.text:='Siento tolerancia, compasión y amor por todos, también por mí.';
if oeg=55 then edit14.text:='Solo tomo alimentos sanos.';
if oeg=56 then edit14.text:='Soy bello y todos me aman.';
if oeg=57 then edit14.text:='Soy bondadoso y tierno conmigo.';
if oeg=58 then edit14.text:='Soy capaz de amar y soy digno de ser amado.';
if oeg>59 then edit14.text:='Soy capaz de pedir lo que quiero fácilmente y con amor.';
 oeg:=random(70);
if oeg<2 then edit17.text:='Soy capaz de sentir y eso me gusta.';
if oeg=3 then edit17.text:='Soy compasivo ante las debilidades de los seres que me rodean.';
if oeg=4 then edit17.text:='Soy coordinación, habilidad y armonía.';
if oeg=5 then edit17.text:='Soy decidido en mente y acción.';
if oeg=6 then edit17.text:='Soy digno y valioso.';
if oeg=7 then edit17.text:='Soy el centro de mis propias fuerzas de curación.';
if oeg=8 then edit17.text:='Soy el discernimiento y así puedo elegir cuidadosamente lo que valga la pena aprender.';
if oeg=9 then edit17.text:='Soy el único responsable de mi desarrollo.';
if oeg=10 then edit17.text:='Soy eternamente joven de espíritu.';
if oeg=11 then edit17.text:='Soy feliz en la intimidad.';
if oeg=12 then edit17.text:='Soy fuerte y capaz de manejar toda situación.';
if oeg=13 then edit17.text:='Soy fuerte y capaz.';
if oeg=14 then edit17.text:='Soy guiado y protegido, tanto en vigilia como en sueños.';
if oeg=15 then edit17.text:='Soy honesto conmigo mismo.';
if oeg=16 then edit17.text:='Soy inmensamente valioso.';
if oeg=17 then edit17.text:='Soy inocente.';
if oeg=18 then edit17.text:='Soy la alegría de la vida que se expresa y recibe.';
if oeg=19 then edit17.text:='Soy la alegría de vivir que se expresa y recibe.';
if oeg=20 then edit17.text:='Soy la persona que siempre quise ser.';
if oeg=21 then edit17.text:='Soy libre de ser yo mismo.';
if oeg=22 then edit17.text:='Soy libre.';
if oeg=23 then edit17.text:='Soy paciente ante las acciones de mis hermanos.';
if oeg=24 then edit17.text:='Soy poderoso, estoy a salvo y seguro.';
if oeg=25 then edit17.text:='Soy quien maneja mis emociones.';
if oeg=26 then edit17.text:='Soy suficiente y lo que hago es suficiente.';
if oeg=27 then edit17.text:='Soy tolerante con la imperfección.';
if oeg=28 then edit17.text:='Soy un ser dotado de pureza.';
if oeg=29 then edit17.text:='Soy una buena persona sienta lo que sienta.';
if oeg=30 then edit17.text:='Soy una buena persona, merezco una buena vida.';
if oeg=31 then edit17.text:='Soy una criatura amada del Universo.';
if oeg=32 then edit17.text:='Soy una persona digna de amor, de respeto y de aceptación.';
if oeg=33 then edit17.text:='Soy uno con Dios y soy inocente. Esa es mi fuerza.';
if oeg=34 then edit17.text:='Soy uno con la fuerza universal que hay dentro de mí.';
if oeg=35 then edit17.text:='Tengo buen carácter natural.';
if oeg=36 then edit17.text:='Tengo calma interior.';
if oeg=37 then edit17.text:='Tengo claro el sentido de mi vida y la dirección del futuro que sigue.';
if oeg=38 then edit17.text:='Tengo confianza en todo lo que hago.';
if oeg=39 then edit17.text:='Tengo derecho a que mis necesidades sean satisfechas.';
if oeg=40 then edit17.text:='Tengo fe en el correcto desarrollo de mi destino.';
if oeg=41 then edit17.text:='Tengo la mente clara y tranquila.';
if oeg=42 then edit17.text:='Tengo mi interés puesto en el presente.';
if oeg=43 then edit17.text:='Tengo paz interior y me abro a escuchar a otros.';
if oeg=44 then edit17.text:='Tengo pensamientos claros.';
if oeg=45 then edit17.text:='Tengo poder para triunfar.';
if oeg=46 then edit17.text:='Tengo presente lo mucho que mi Padre me necesita.';
if oeg=47 then edit17.text:='Tengo todo lo que necesito para conseguir todo lo que quiero.';
if oeg=48 then edit17.text:='Tengo una actitud atenta en la ayuda.';
if oeg=49 then edit17.text:='Tengo una actitud dulce en la expresión.';
if oeg=50 then edit17.text:='Tengo una actitud tolerante en la relación.';
if oeg=51 then edit17.text:='Tengo una actitud tranquila en la acción y paciente en el trato.';
if oeg=52 then edit17.text:='Tengo una motivación: ¡Vivir!';
if oeg=53 then edit17.text:='Tengo una saludable actitud ante los problemas de los otros.';
if oeg=54 then edit17.text:='Todo está bien en mi mundo.';
if oeg=55 then edit17.text:='Tomo conciencia de mis reacciones con amabilidad y sin juzgarme.';
if oeg=56 then edit17.text:='Trasmito amor a todo mi cuerpo, mis células y todo el universo.';
if oeg=57 then edit17.text:='Veo el mundo desde la inocencia.';
if oeg=58 then edit17.text:='Veo la armonía del universo en cada ser.';
if oeg=59 then edit17.text:='Vivo armónicamente conmigo y con mi entorno.';
if oeg=60 then edit17.text:='Vivo con facilidad y alegría.';
if oeg=61 then edit17.text:='Vivo el presente.';
if oeg=62 then edit17.text:='Vivo en armonía con todo el planeta.';
if oeg=63 then edit17.text:='Vivo este día como si fuera el último de mi existencia.';
if oeg=64 then edit17.text:='Vivo feliz cada instante de mi vida.';
if oeg=65 then edit17.text:='Vivo lleno de paz y tranquilidad interior.';
if oeg=66 then edit17.text:='Vivo mi sexualidad de modo inocente.';
if oeg=67 then edit17.text:='Voy más allá de las limitaciones de mis padres.';
if oeg=68 then edit17.text:='Ya no culpo a los demás. Acepto la total responsabilidad de todo lo que yo he hecho.';
if oeg>69 then edit17.text:='Yo soy poderoso e influyente en mi mundo.';

oeg:=random(60);
if oeg<2 then Edit1.text:='¡Tengo una paz increíble!';
if oeg=3 then Edit1.text:='Abandono todos mis conflictos internos a fin de que venga a mí la paz mental.';
if oeg=4 then Edit1.text:='Abandono todos mis juicios y mi tendencia a hacer comparaciones.';
if oeg=5 then Edit1.text:='Abriré mi corazón y me perdonaré.';
if oeg=6 then Edit1.text:='Abro mi corazón y acepto a los demás como son.';
if oeg=7 then Edit1.text:='Abro mi corazón y me regocijo en lo que soy.';
if oeg=8 then Edit1.text:='Abro mi imaginación para crear el mejor de los mundos para mí mismo.';
if oeg=9 then Edit1.text:='Acepto a los demás tal como son.';
if oeg=10 then Edit1.text:='Acepto con confianza mi grandeza y mantengo siempre esta autoestima.';
if oeg=11 then Edit1.text:='Acepto el amor de todos los que lo ofrezcan.';
if oeg=12 then Edit1.text:='Acepto el milagro de la curación y permito ser totalmente curado.';
if oeg=13 then Edit1.text:='Acepto el placer como parte de mí ser.';
if oeg=14 then Edit1.text:='Acepto la felicidad y la salvación ahora.';
if oeg=15 then Edit1.text:='Acepto las opiniones o criterios dispares de los míos.';
if oeg=16 then Edit1.text:='Acepto mis imperfecciones.';
if oeg=17 then Edit1.text:='Acepto mis limitaciones interiores.';
if oeg=18 then Edit1.text:='Ahora me permito Ser Feliz.';
if oeg=19 then Edit1.text:='Ahora todo lo que necesito viene a mí.';
if oeg=20 then Edit1.text:='Ahora trasciendo mis viejos miedos y limitaciones.';
if oeg=21 then Edit1.text:='Amo al ser que está en mí.';
if oeg=22 then Edit1.text:='Amo sin esperar nada a cambio.';
if oeg=23 then Edit1.text:='Amo y soy amado.';
if oeg=24 then Edit1.text:='Aprendo a escuchar y a confiar en mi voz interior.';
if oeg=25 then Edit1.text:='Aprendo algo nuevo con cada experiencia.';
if oeg=26 then Edit1.text:='Asumo el cuidado de mi mismo todo el tiempo.';
if oeg=27 then Edit1.text:='Asumo la responsabilidad de mi propia vida. Soy Libre.';
if oeg=28 then Edit1.text:='Atraigo gente con la moral muy alta.';
if oeg=29 then Edit1.text:='Busco el amor y lo encuentro en todas partes.';
if oeg=30 then Edit1.text:='Comparto mi afecto y mi gozo.';
if oeg=31 then Edit1.text:='Comparto mi amor con los demás.';
if oeg=32 then Edit1.text:='Comprendo todo aquello que debo saber o comprender.';
if oeg=33 then Edit1.text:='Con alegría acepto y muestro el niño que hay en mí.';
if oeg=34 then Edit1.text:='Con facilidad y amor pido lo que necesito.';
if oeg=35 then Edit1.text:='Confío en el éxito final.';
if oeg=36 then Edit1.text:='Confió en el proceso de la vida.';
if oeg=37 then Edit1.text:='Confió en mi guía interior.';
if oeg=38 then Edit1.text:='Confió en mi mismo, confió en mi intuición.';
if oeg=39 then Edit1.text:='Confío en mí.';
if oeg=40 then Edit1.text:='Confío en que el proceso de la vida cuidará de mí.';
if oeg=41 then Edit1.text:='Conservo mis pensamientos claros y tranquilos en los grupos.';
if oeg=42 then Edit1.text:='Consigo que nadie enturbie mi mirada.';
if oeg=43 then Edit1.text:='Creo en mis hermanos y los acepto, los respaldo y los valoro.';
if oeg=44 then Edit1.text:='Creo la paz en mi mente, mi cuerpo y mi mundo.';
if oeg=45 then Edit1.text:='Cuanto más amor doy, más amor recibo.';
if oeg=46 then Edit1.text:='Decido ver las cosas de manera diferente.';
if oeg=47 then Edit1.text:='Decido vivir en el presente siempre jubiloso.';
if oeg=48 then Edit1.text:='Declaro la paz y la armonía en mi interior y a mí alrededor.';
if oeg=49 then Edit1.text:='Dejo el pasado y avanzo hacia lo nuevo.';
if oeg=50 then Edit1.text:='Dejo partir mis conductas autodestructivas.';
if oeg=51 then Edit1.text:='Dejo partir mis conductas emocionales y físicas.';
if oeg=52 then Edit1.text:='Dejo partir mis viejos pensamientos. Lo pasado es pasado. Estoy en paz.';
if oeg=53 then Edit1.text:='Dejo que el amor llegue a mi vida y me llene de felicidad y alegría.';
if oeg=54 then Edit1.text:='Dejo que la Vida fluya a través de mí.';
if oeg=55 then Edit1.text:='Dejo que salgan todos los bloqueos de energía.';
if oeg=56 then Edit1.text:='Descubro lo maravilloso que soy.';
if oeg=57 then Edit1.text:='Descubro mi propio don y lo realizo.';
if oeg=58 then Edit1.text:='Deseo estar tranquilo.';
if oeg>59 then Edit1.text:='Deshago todos mis pensamientos erróneos.';
 oeg:=random(60);
if oeg<2 then Edit2.text:='Despierto mis poderes internos de autocuración.';
if oeg=3 then Edit2.text:='Disfruto compartir con otros.';
if oeg=4 then Edit2.text:='Disfruto con mi sexualidad.';
if oeg=5 then Edit2.text:='Disfruto de ser libre y abierto a la bondad que me rodea.';
if oeg=6 then Edit2.text:='Disfruto totalmente de todo lo que hago.';
if oeg=7 then Edit2.text:='Doy a mi vida una finalidad y un destino.';
if oeg=8 then Edit2.text:='Doy de todo corazón y alegremente y agradezco el privilegio de poder hacerlo.';
if oeg=9 then Edit2.text:='Doy mi vida a mi niño interior bello y puro.';
if oeg=10 then Edit2.text:='Elevo mi energía sexual.';
if oeg=11 then Edit2.text:='Elijo aceptarme y amarme.';
if oeg=12 then Edit2.text:='Elijo dejar que Dios decida por mí.';
if oeg=13 then Edit2.text:='Elijo el amor como meta de felicidad.';
if oeg=14 then Edit2.text:='Elijo la paz en lugar del conflicto.';
if oeg=15 then Edit2.text:='Elijo llenar mi mundo de alegría.';
if oeg=16 then Edit2.text:='En cada momento soy libre para decidir.';
if oeg=17 then Edit2.text:='Encuentro dentro de mí lo que busco.';
if oeg=18 then Edit2.text:='Encuentro en mi interior mi verdadera identidad.';
if oeg=19 then Edit2.text:='Encuentro la paz en mi interior.';
if oeg=20 then Edit2.text:='Encuentro mi camino y lo sigo con absoluta fe y confianza.';
if oeg=21 then Edit2.text:='Encuentro mi propio ritmo.';
if oeg=22 then Edit2.text:='Encuentro mi verdadera identidad.';
if oeg=23 then Edit2.text:='Encuentro seguridad en mi interior.';
if oeg=24 then Edit2.text:='Entiendo que el camino que recorro es el camino que yo he elegido.';
if oeg=25 then Edit2.text:='Escojo hacer que mi vida sea sencilla, fácil y gozosa.';
if oeg=26 then Edit2.text:='Escojo vivir en el espacio abierto de mi corazón.';
if oeg=27 then Edit2.text:='Escucho mi voz interna. Ella me habla.';
if oeg=28 then Edit2.text:='Escucho mis sentimientos y los expreso en forma apropiada.';
if oeg=29 then Edit2.text:='Está bien expresar todas mis emociones.';
if oeg=30 then Edit2.text:='Estoy a salvo, me relajo y dejo que la vida fluya jubilosamente.';
if oeg=31 then Edit2.text:='Estoy a salvo.';
if oeg=32 then Edit2.text:='Estoy abierto a la sabiduría interior.';
if oeg=33 then Edit2.text:='Estoy abierto a nuevas experiencias.';
if oeg=34 then Edit2.text:='Estoy abierto y receptivo a todos los puntos de vista.';
if oeg=35 then Edit2.text:='Estoy consciente de cada instante de mi vida.';
if oeg=36 then Edit2.text:='Estoy convencido de que mi curación será efectiva.';
if oeg=37 then Edit2.text:='Estoy dispuesto a avanzar con soltura.';
if oeg=38 then Edit2.text:='Estoy dispuesto a curarme.';
if oeg=39 then Edit2.text:='Estoy dispuesto a tener éxito aunque suponga agradar a mis padres.';
if oeg=40 then Edit2.text:='Estoy en manos de Dios.';
if oeg=41 then Edit2.text:='Estoy en paz con todas mis emociones, me amo y me apruebo.';
if oeg=42 then Edit2.text:='Estoy en paz con todos los aspectos de mi vida.';
if oeg=43 then Edit2.text:='Estoy en paz.';
if oeg=44 then Edit2.text:='Estoy libre de la influencia de traumas pasados.';
if oeg=45 then Edit2.text:='Estoy lleno de energía y entusiasmo por la vida.';
if oeg=46 then Edit2.text:='Estoy lleno de energía y entusiasmo.';
if oeg=47 then Edit2.text:='Estoy rodeado de amor y lleno de paz.';
if oeg=48 then Edit2.text:='Estoy sano, delgado y satisfecho.';
if oeg=49 then Edit2.text:='Estoy seguro al ser yo.';
if oeg=50 then Edit2.text:='Estoy seguro de mi capacidad de expresión.';
if oeg=51 then Edit2.text:='Estoy seguro y a salvo cuando expreso mis sentimientos.';
if oeg=52 then Edit2.text:='Estoy siempre a salvo y protegido.';
if oeg=53 then Edit2.text:='Estoy totalmente abierto a un nuevo camino.';
if oeg=54 then Edit2.text:='Expreso con facilidad mis sentimientos.';
if oeg=55 then Edit2.text:='Expreso confianza en lo que digo y hago.';
if oeg=56 then Edit2.text:='Expreso mi belleza y amor en todo lo que hago.';
if oeg=57 then Edit2.text:='Expreso mi propia belleza y amor en todo lo que hago.';
if oeg=58 then Edit2.text:='Fluyo fácilmente con el cambio.';
if oeg>59 then Edit2.text:='Fluyo suavemente con la vida y en cada experiencia.';
 oeg:=random(60);
if oeg<2 then Edit3.text:='Hablo con fluidez.';
if oeg=3 then Edit3.text:='He sido creado perfecto y sigo así.';
if oeg=4 then Edit3.text:='Hoy capto la maravilla y gloria de la vida con nuevos ojos.';
if oeg=5 then Edit3.text:='Hoy comienzo una nueva vida.';
if oeg=6 then Edit3.text:='Hoy descubro qué hago mejor, lo hago y disfruto haciéndolo.';
if oeg=7 then Edit3.text:='Hoy es el día en que comienzo a hacer todas las cosas que deseé.';
if oeg=8 then Edit3.text:='Hoy quiero trabajar la amabilidad, la bondad y la condescendencia.';
if oeg=9 then Edit3.text:='Hoy sigo la voluntad de mi Padre.';
if oeg=10 then Edit3.text:='Hoy sigo mi propio criterio, sin despreciar el ajeno.';
if oeg=11 then Edit3.text:='Hoy trabajaré con la más pura de mis intenciones en mayor beneficio de todos.';
if oeg=12 then Edit3.text:='Impulso mi vida con la energía que genero en el presente.';
if oeg=13 then Edit3.text:='Irradio paz, calma y optimismo.';
if oeg=14 then Edit3.text:='Jamás fracasaré porque he determinado triunfar.';
if oeg=15 then Edit3.text:='Limpio mi cuerpo y mi ser continuamente.';
if oeg=16 then Edit3.text:='Lleno mi corazón de paz y felicidad.';
if oeg=17 then Edit3.text:='Me abro a una nueva vida.';
if oeg=18 then Edit3.text:='Me acepto tal y como soy.';
if oeg=19 then Edit3.text:='Me acepto y me apruebo tal cual soy.';
if oeg=20 then Edit3.text:='Me acepto y me apruebo.';
if oeg=21 then Edit3.text:='Me amo a mi mismo pase lo que pase.';
if oeg=22 then Edit3.text:='Me amo a mí mismo.';
if oeg=23 then Edit3.text:='Me amo tal y como soy.';
if oeg=24 then Edit3.text:='Me amo y me apruebo.';
if oeg=25 then Edit3.text:='Me amo y me apruebo. Soy perfecto. Estoy en paz.';
if oeg=26 then Edit3.text:='Me atrevo a ver mi propio valor.';
if oeg=27 then Edit3.text:='Me comunico fácil y alegremente.';
if oeg=28 then Edit3.text:='Me doy permiso para cambiar.';
if oeg=29 then Edit3.text:='Me doy permiso para disfrutar de mi cuerpo.';
if oeg=30 then Edit3.text:='Me doy permiso para disfrutar totalmente de todo lo que hago.';
if oeg=31 then Edit3.text:='Me doy permiso para estar en paz.';
if oeg=32 then Edit3.text:='Me doy permiso para realizarme.';
if oeg=33 then Edit3.text:='Me doy permiso para ser próspero y feliz.';
if oeg=34 then Edit3.text:='Me encanta ser quien soy y hago valer mi poder con prudencia.';
if oeg=35 then Edit3.text:='Me estoy limpiando de todos los residuos negativos.';
if oeg=36 then Edit3.text:='Me expreso como soy fácilmente.';
if oeg=37 then Edit3.text:='Me hallo en paz sabiendo que estoy protegido y guiado en todo momento.';
if oeg=38 then Edit3.text:='Me liberaré de mis dudas recordando que hay una razón para todo lo que sucede.';
if oeg=39 then Edit3.text:='Me libero de la necesidad de criticar a los demás.';
if oeg=40 then Edit3.text:='Me libero de mis adicciones.';
if oeg=41 then Edit3.text:='Me libero de mis programas del pasado.';
if oeg=42 then Edit3.text:='Me libero de todo lo que limite mi desarrollo.';
if oeg=43 then Edit3.text:='Me libero de todo lo que me hace daño.';
if oeg=44 then Edit3.text:='Me libero del dolor y el sufrimiento.';
if oeg=45 then Edit3.text:='Me libero del pasado.';
if oeg=46 then Edit3.text:='Me lleno de saber para poder ayudar sabiamente.';
if oeg=47 then Edit3.text:='Me perdono a mí mismo y decido por la felicidad.';
if oeg=48 then Edit3.text:='Me perdono a mi mismo.';
if oeg=49 then Edit3.text:='Me perdono completamente.';
if oeg=50 then Edit3.text:='Me perdono por mis limitaciones.';
if oeg=51 then Edit3.text:='Me permito estar conmigo mismo.';
if oeg=52 then Edit3.text:='Me permito ser como soy.';
if oeg=53 then Edit3.text:='Me quiero en presencia de los demás.';
if oeg=54 then Edit3.text:='Me realizo creativamente.';
if oeg=55 then Edit3.text:='Me respeto a mí mismo todo el tiempo.';
if oeg=56 then Edit3.text:='Me rindo al amor.';
if oeg=57 then Edit3.text:='Me siento amado y protegido.';
if oeg=58 then Edit3.text:='Me siento bien y me sonrío.';
if oeg>59 then edit3.text:='Me siento despierto y fresco.';
 oeg:=random(60);
if oeg<2 then Edit4.text:='Me siento dichoso porque conozco el amor y soy amado.';
if oeg=3 then Edit4.text:='Me siento feliz conmigo mismo.';
if oeg=4 then Edit4.text:='Me siento muy a gusto siguiendo una dieta sana.';
if oeg=5 then Edit4.text:='Me siento seguro compartiendo mis sentimientos.';
if oeg=6 then Edit4.text:='Me siento seguro recibiendo.';
if oeg=7 then Edit4.text:='Me uno cada vez y cada día más a Dios.';
if oeg=8 then Edit4.text:='Merezco felicidad y gozo.';
if oeg=9 then Edit4.text:='Merezco lo mejor de la vida.';
if oeg=10 then Edit4.text:='Merezco lo mejor para mi vida.';
if oeg=11 then Edit4.text:='Merezco que se me den las cosas que necesito.';
if oeg=12 then Edit4.text:='Merezco relaciones divertidas, fáciles y que me apoyen.';
if oeg=13 then Edit4.text:='Merezco ser amado.';
if oeg=14 then Edit4.text:='Merezco ser feliz.';
if oeg=15 then Edit4.text:='Merezco tenerlo todo.';
if oeg=16 then Edit4.text:='Mi aprendizaje aparece de forma distinta y en sitios y con gentes diferentes.';
if oeg=17 then Edit4.text:='Mi corazón está repleto de fuerza y confianza.';
if oeg=18 then Edit4.text:='Mi hogar es el Universo.';
if oeg=19 then Edit4.text:='Miro tranquilo hacia lo profundo de mí ser.';
if oeg=20 then Edit4.text:='Mis ingresos aumentan constantemente.';
if oeg=21 then Edit4.text:='Nadie tiene razón ni se equivoca. Voy más allá de mi juicio.';
if oeg=22 then Edit4.text:='No necesito perseguir nada con el fin de estar completo.';
if oeg=23 then Edit4.text:='No necesito sufrir para conseguir la felicidad.';
if oeg=24 then Edit4.text:='No soy inútil, sino alguien todopoderoso.';
if oeg=25 then Edit4.text:='Ofrezco a los demás lo que he recibido.';
if oeg=26 then Edit4.text:='Perdono con facilidad.';
if oeg=27 then Edit4.text:='Permito que mis pensamientos sean libres.';
if oeg=28 then Edit4.text:='Pienso, hago y consigo cosas positivas.';
if oeg=29 then Edit4.text:='Pongo mis talentos al servicio de un todo mayor.';
if oeg=30 then Edit4.text:='Pongo todo mi ser en cada acto de la vida.';
if oeg=31 then Edit4.text:='Poseo energía y vitalidad para mis tareas de vida.';
if oeg=32 then Edit4.text:='Practico la moderación en pensamiento y acción.';
if oeg=33 then Edit4.text:='Puedo comunicar mi amor con el lenguaje del silencio.';
if oeg=34 then Edit4.text:='Puedo hacerlo, lo haré y lo hago.';
if oeg=35 then Edit4.text:='Puedo sentir como la vida es más y más intensa y hermosa.';
if oeg=36 then Edit4.text:='Reafirmo todo mi poder personal.';
if oeg=37 then Edit4.text:='Reclamo mi poder ahora.';
if oeg=38 then Edit4.text:='Reconozco las necesidades de mi cuerpo.';
if oeg=39 then Edit4.text:='Reconozco los mensajes de mi cuerpo.';
if oeg=40 then Edit4.text:='Recuerdo siempre que el propósito de mi relación es compartir la luz y dar felicidad.';
if oeg=41 then Edit4.text:='Respeto el territorio de cada uno.';
if oeg=42 then Edit4.text:='Respeto la libertad y necesidades de los que amo.';
if oeg=43 then Edit4.text:='Respeto las creencias de los demás.';
if oeg=44 then Edit4.text:='Respondo a las necesidades de otros sin alterar mi ser interior.';
if oeg=45 then Edit4.text:='Restituyo mi energía bloqueada.';
if oeg=46 then Edit4.text:='Revitalizo mi cuerpo y mi espíritu.';
if oeg=47 then Edit4.text:='Satisfago plenamente todas mis necesidades.';
if oeg=48 then Edit4.text:='Siempre estoy seguro y a salvo completamente en mi cuerpo físico.';
if oeg=49 then Edit4.text:='Siempre tomo el camino correcto.';
if oeg=50 then Edit4.text:='Siento fortaleza y coraje interno.';
if oeg=51 then Edit4.text:='Siento la vida llena de alegría y de amor.';
if oeg=52 then Edit4.text:='Siento mi armonía interna.';
if oeg=53 then Edit4.text:='Siento mi fortaleza interna.';
if oeg=54 then Edit4.text:='Siento tolerancia, compasión y amor por todos, también por mí.';
if oeg=55 then Edit4.text:='Solo tomo alimentos sanos.';
if oeg=56 then Edit4.text:='Soy bello y todos me aman.';
if oeg=57 then Edit4.text:='Soy bondadoso y tierno conmigo.';
if oeg=58 then Edit4.text:='Soy capaz de amar y soy digno de ser amado.';
if oeg>59 then Edit4.text:='Soy capaz de pedir lo que quiero fácilmente y con amor.';
 oeg:=random(70);
if oeg<2 then Edit5.text:='Soy capaz de sentir y eso me gusta.';
if oeg=3 then Edit5.text:='Soy compasivo ante las debilidades de los seres que me rodean.';
if oeg=4 then Edit5.text:='Soy coordinación, habilidad y armonía.';
if oeg=5 then Edit5.text:='Soy decidido en mente y acción.';
if oeg=6 then Edit5.text:='Soy digno y valioso.';
if oeg=7 then Edit5.text:='Soy el centro de mis propias fuerzas de curación.';
if oeg=8 then Edit5.text:='Soy el discernimiento y así puedo elegir cuidadosamente lo que valga la pena aprender.';
if oeg=9 then Edit5.text:='Soy el único responsable de mi desarrollo.';
if oeg=10 then Edit5.text:='Soy eternamente joven de espíritu.';
if oeg=11 then Edit5.text:='Soy feliz en la intimidad.';
if oeg=12 then Edit5.text:='Soy fuerte y capaz de manejar toda situación.';
if oeg=13 then Edit5.text:='Soy fuerte y capaz.';
if oeg=14 then Edit5.text:='Soy guiado y protegido, tanto en vigilia como en sueños.';
if oeg=15 then Edit5.text:='Soy honesto conmigo mismo.';
if oeg=16 then Edit5.text:='Soy inmensamente valioso.';
if oeg=17 then Edit5.text:='Soy inocente.';
if oeg=18 then Edit5.text:='Soy la alegría de la vida que se expresa y recibe.';
if oeg=19 then Edit5.text:='Soy la alegría de vivir que se expresa y recibe.';
if oeg=20 then Edit5.text:='Soy la persona que siempre quise ser.';
if oeg=21 then Edit5.text:='Soy libre de ser yo mismo.';
if oeg=22 then Edit5.text:='Soy libre.';
if oeg=23 then Edit5.text:='Soy paciente ante las acciones de mis hermanos.';
if oeg=24 then Edit5.text:='Soy poderoso, estoy a salvo y seguro.';
if oeg=25 then Edit5.text:='Soy quien maneja mis emociones.';
if oeg=26 then Edit5.text:='Soy suficiente y lo que hago es suficiente.';
if oeg=27 then Edit5.text:='Soy tolerante con la imperfección.';
if oeg=28 then Edit5.text:='Soy un ser dotado de pureza.';
if oeg=29 then Edit5.text:='Soy una buena persona sienta lo que sienta.';
if oeg=30 then Edit5.text:='Soy una buena persona, merezco una buena vida.';
if oeg=31 then Edit5.text:='Soy una criatura amada del Universo.';
if oeg=32 then Edit5.text:='Soy una persona digna de amor, de respeto y de aceptación.';
if oeg=33 then Edit5.text:='Soy uno con Dios y soy inocente. Esa es mi fuerza.';
if oeg=34 then Edit5.text:='Soy uno con la fuerza universal que hay dentro de mí.';
if oeg=35 then Edit5.text:='Tengo buen carácter natural.';
if oeg=36 then Edit5.text:='Tengo calma interior.';
if oeg=37 then Edit5.text:='Tengo claro el sentido de mi vida y la dirección del futuro que sigue.';
if oeg=38 then Edit5.text:='Tengo confianza en todo lo que hago.';
if oeg=39 then Edit5.text:='Tengo derecho a que mis necesidades sean satisfechas.';
if oeg=40 then Edit5.text:='Tengo fe en el correcto desarrollo de mi destino.';
if oeg=41 then Edit5.text:='Tengo la mente clara y tranquila.';
if oeg=42 then Edit5.text:='Tengo mi interés puesto en el presente.';
if oeg=43 then Edit5.text:='Tengo paz interior y me abro a escuchar a otros.';
if oeg=44 then Edit5.text:='Tengo pensamientos claros.';
if oeg=45 then Edit5.text:='Tengo poder para triunfar.';
if oeg=46 then Edit5.text:='Tengo presente lo mucho que mi Padre me necesita.';
if oeg=47 then Edit5.text:='Tengo todo lo que necesito para conseguir todo lo que quiero.';
if oeg=48 then Edit5.text:='Tengo una actitud atenta en la ayuda.';
if oeg=49 then Edit5.text:='Tengo una actitud dulce en la expresión.';
if oeg=50 then Edit5.text:='Tengo una actitud tolerante en la relación.';
if oeg=51 then Edit5.text:='Tengo una actitud tranquila en la acción y paciente en el trato.';
if oeg=52 then Edit5.text:='Tengo una motivación: ¡Vivir!';
if oeg=53 then Edit5.text:='Tengo una saludable actitud ante los problemas de los otros.';
if oeg=54 then Edit5.text:='Todo está bien en mi mundo.';
if oeg=55 then Edit5.text:='Tomo conciencia de mis reacciones con amabilidad y sin juzgarme.';
if oeg=56 then Edit5.text:='Trasmito amor a todo mi cuerpo, mis células y todo el universo.';
if oeg=57 then Edit5.text:='Veo el mundo desde la inocencia.';
if oeg=58 then Edit5.text:='Veo la armonía del universo en cada ser.';
if oeg=59 then Edit5.text:='Vivo armónicamente conmigo y con mi entorno.';
if oeg=60 then Edit5.text:='Vivo con facilidad y alegría.';
if oeg=61 then Edit5.text:='Vivo el presente.';
if oeg=62 then Edit5.text:='Vivo en armonía con todo el planeta.';
if oeg=63 then Edit5.text:='Vivo este día como si fuera el último de mi existencia.';
if oeg=64 then Edit5.text:='Vivo feliz cada instante de mi vida.';
if oeg=65 then Edit5.text:='Vivo lleno de paz y tranquilidad interior.';
if oeg=66 then Edit5.text:='Vivo mi sexualidad de modo inocente.';
if oeg=67 then Edit5.text:='Voy más allá de las limitaciones de mis padres.';
if oeg=68 then Edit5.text:='Ya no culpo a los demás. Acepto la total responsabilidad de todo lo que yo he hecho.';
if oeg>69 then Edit5.text:='Yo soy poderoso e influyente en mi mundo.';
end;

procedure Tondas_frm.Button4Click(Sender: TObject);
begin
Label1.Caption := Edit12.Text;
Label2.Caption := Edit15.Text;
Label3.Caption := Edit16.Text;
Label4.Caption := Edit14.Text;
Label5.Caption := Edit17.Text;
Label6.Caption := Edit1.Text;
Label7.Caption := Edit2.Text;
Label8.Caption := Edit3.Text;
Label9.Caption := Edit4.Text;
Label10.Caption := Edit5.Text;
GroupBox1.Visible := False;
Timer3.Enabled := True;
TResonancias.Enabled := True;
end;

procedure Tondas_frm.Timer3Timer(Sender: TObject);
begin
ChangingPulses(50000,555,11111,5,1,2,
 '00000000','00000000');
 ran33:=random(42);
 if ran33<3 then image1.picture.LoadFromFile('orgon26.jpg');
 if ran33=3 then image1.picture.LoadFromFile('orgon13.jpg');
    if ran33=4 then image1.picture.LoadFromFile('fundir.jpg');
    if ran33=5 then image1.picture.LoadFromFile('orgon01.jpg');
    if ran33=6 then image1.picture.LoadFromFile('orgon14.jpg');
    if ran33=7 then image1.picture.LoadFromFile('orgon27.jpg');
    if ran33=8 then image1.picture.LoadFromFile('vitruvian_ceno.jpg');
    if ran33=9 then image1.picture.LoadFromFile('orgon02.jpg');
    if ran33=10 then image1.picture.LoadFromFile('orgon15.jpg');
    if ran33=11 then image1.picture.LoadFromFile('vitruvian_energetica.jpg');
    if ran33=12 then image1.picture.LoadFromFile('orgon03.jpg');
    if ran33=13 then image1.picture.LoadFromFile('orgon16.jpg');
    if ran33=14 then image1.picture.LoadFromFile('vitruvian_corona.jpg');
    if ran33=15 then image1.picture.LoadFromFile('orgon04.jpg');
    if ran33=16 then image1.picture.LoadFromFile('orgon17.jpg');
    if ran33=17 then image1.picture.LoadFromFile('vitruvian_garganta.jpg');
    if ran33=18 then image1.picture.LoadFromFile('orgon05.jpg');
    if ran33=19 then image1.picture.LoadFromFile('orgon18.jpg');
    if ran33=20 then image1.picture.LoadFromFile('vitruvian_base.jpg');
    if ran33=21 then image1.picture.LoadFromFile('orgon06.jpg');
    if ran33=22 then image1.picture.LoadFromFile('orgon19.jpg');
    if ran33=23 then image1.picture.LoadFromFile('vitruvian_estomago.jpg');
    if ran33=24 then image1.picture.LoadFromFile('orgon07.jpg');
    if ran33=25 then image1.picture.LoadFromFile('orgon20.jpg');
    if ran33=26 then image1.picture.LoadFromFile('vitruvian_armonia3.jpg');
    if ran33=27 then image1.picture.LoadFromFile('orgon08.jpg');
    if ran33=28 then image1.picture.LoadFromFile('orgon21.jpg');
    if ran33=29 then image1.picture.LoadFromFile('vitruvian_armonia2.jpg');
    if ran33=30 then image1.picture.LoadFromFile('orgon09.jpg');
    if ran33=31 then image1.picture.LoadFromFile('orgon22.jpg');
    if ran33=32 then image1.picture.LoadFromFile('vitruvian_armonia1.jpg');
    if ran33=33 then image1.picture.LoadFromFile('orgon10.jpg');
    if ran33=34 then image1.picture.LoadFromFile('orgon23.jpg');
    if ran33=35 then image1.picture.LoadFromFile('aura_scan.jpg');
    if ran33=36 then image1.picture.LoadFromFile('orgon11.jpg');
    if ran33=37 then image1.picture.LoadFromFile('orgon24.jpg');
    if ran33=38 then image1.picture.LoadFromFile('vitruvian_armonia2.jpg');
    if ran33=39 then image1.picture.LoadFromFile('orgon12.jpg');
    if ran33>39 then image1.picture.LoadFromFile('orgon25.jpg');
    image1.refresh;
If CheckBox1.Checked = True Then Begin
Button3.Click;
ChangingPulses(5555,555,55555,5,5,1,
 '11111111','11111111');
Button4.Click;
end;
ChangingPulses(50000,555,11111,5,1,2,
 '00000000','00000000');
end;

procedure Tondas_frm.Label11Click(Sender: TObject);
begin
Timer3.Enabled := False;
TResonancias.Enabled := False;
GroupBox1.Visible := True;
end;

procedure Tondas_frm.Panel2Click(Sender: TObject);
begin
GroupBox1.Visible := False;
Timer3.Enabled := True;
TResonancias.Enabled := True;
end;

procedure Tondas_frm.FormClose(Sender: TObject; var Action: TCloseAction);
begin
MyChrono.Stop;
Timer3.enabled := False;
TResonancias.enabled := false;
end;

procedure Tondas_frm.Edit6Change(Sender: TObject);
begin
If Edit7.Text <> '' Then CheckBox22.Checked := True
Else
CheckBox22.Checked := False;
end;

procedure Tondas_frm.LimpiarResonancias();
begin
CheckBox2.Checked := False;
CheckBox3.Checked := False;
CheckBox4.Checked := False;
CheckBox5.Checked := False;
CheckBox6.Checked := False;
CheckBox7.Checked := False;
CheckBox8.Checked := False;
CheckBox9.Checked := False;
CheckBox10.Checked := False;
CheckBox12.Checked := False;
CheckBox13.Checked := False;
CheckBox14.Checked := False;
CheckBox15.Checked := False;
CheckBox16.Checked := False;
CheckBox17.Checked := False;
CheckBox18.Checked := False;
CheckBox19.Checked := False;
CheckBox20.Checked := False;
CheckBox21.Checked := False;
CheckBox23.Checked := False;
CheckBox24.Checked := False;
CheckBox25.Checked := False;
CheckBox26.Checked := False; 
CheckBox27.Checked := False;
CheckBox28.Checked := False;
CheckBox29.Checked := False;
CheckBox30.Checked := False;
CheckBox31.Checked := False;
CheckBox32.Checked := False;
CheckBox33.Checked := False;
CheckBox34.Checked := False;
CheckBox35.Checked := False;
CheckBox36.Checked := False;
CheckBox37.Checked := False;
end;

procedure Tondas_frm.TResonanciasTimer(Sender: TObject);
begin
LimpiarResonancias();
ran33 := Random(5);
If ran33 = 3 Then CheckBox2.Checked := True;
ran33 := Random(5);
If ran33 = 3 Then CheckBox3.Checked := True;
ran33 := Random(5);
If ran33 = 3 Then CheckBox4.Checked := True;
ran33 := Random(5);
If ran33 = 3 Then CheckBox5.Checked := True;
ran33 := Random(5);
If ran33 = 3 Then CheckBox6.Checked := True;
ran33 := Random(5);
If ran33 = 3 Then  CheckBox7.Checked := True;
ran33 := Random(5);
If ran33 = 3 Then CheckBox8.Checked := True;
ran33 := Random(5);
If ran33 = 3 Then CheckBox9.Checked := True;
ran33 := Random(5);
If ran33 = 3 Then CheckBox10.Checked := True;
ran33 := Random(5);
If ran33 = 3 Then CheckBox12.Checked := True;
ran33 := Random(5);
If ran33 = 3 Then CheckBox13.Checked := True;
ran33 := Random(5);
If ran33 = 3 Then CheckBox14.Checked := True;
ran33 := Random(5);
If ran33 = 3 Then CheckBox15.Checked := True;
ran33 := Random(5);
If ran33 = 3 Then CheckBox16.Checked := True;
ran33 := Random(5);
If ran33 = 3 Then CheckBox17.Checked := True;
ran33 := Random(5);
If ran33 = 3 Then CheckBox18.Checked := True;
ran33 := Random(5);
If ran33 = 3 Then CheckBox19.Checked := True;
ran33 := Random(5);
If ran33 = 3 Then CheckBox20.Checked := True;
ran33 := Random(5);
If ran33 = 3 Then CheckBox21.Checked := True;
ran33 := Random(5);
If ran33 = 3 Then CheckBox23.Checked := True;
ran33 := Random(5);
If ran33 = 3 Then CheckBox24.Checked := True;
ran33 := Random(5);
If ran33 = 3 Then CheckBox25.Checked := True;
ran33 := Random(5);
If ran33 = 3 Then CheckBox26.Checked := True; 
ran33 := Random(5);
If ran33 = 3 Then CheckBox27.Checked := True;
ran33 := Random(5);
If ran33 = 3 Then CheckBox28.Checked := True;
ran33 := Random(5);
If ran33 = 3 Then CheckBox29.Checked := True;
ran33 := Random(5);
If ran33 = 3 Then CheckBox30.Checked := True;
ran33 := Random(5);
If ran33 = 3 Then CheckBox31.Checked := True;
ran33 := Random(5);
If ran33 = 3 Then CheckBox32.Checked := True;
ran33 := Random(5);
If ran33 = 3 Then CheckBox33.Checked := True;
ran33 := Random(5);
If ran33 = 3 Then CheckBox34.Checked := True;
ran33 := Random(5);
If ran33 = 3 Then CheckBox35.Checked := True;
ran33 := Random(5);
If ran33 = 3 Then CheckBox36.Checked := True;
ran33 := Random(5);
If ran33 = 3 Then CheckBox37.Checked := True;
end;

end.
